### PR TITLE
provide a config to set the output directory

### PR DESCRIPTION
**Pull request by devinfd**

### CODE REVIEW

**Comment by danijelk** [comment]
Thanks @devinfd I Feel the same fallback and default is unnecessary. What about moving it all to config instead?

        $jsLangPath = config('output_directory');

**Comment by devinfd** [comment]
I think it's better only in the config however for backwards compatibility it may need to be `config('output_directory', 'build/lang')`. Otherwise when users upgrade and don't have a output_directory config set, it wont result to `public_path(null)`

I hope that makes sense. Your call though. I'm happy to remove the fallback value from the PR if requested.

**Comment by danijelk** [comment]
No I completely agree with the fallback, now it's just set in 2 places. Having it in config only should be enough, just set that to 'output_directory ' => public_path(...) and it should be all fine 👍🏼

**Comment by danijelk** [comment]
Agree with changes @devinfd ?

**Pull request merged**
